### PR TITLE
Change design of delete icon in ShoppingCartItem

### PR DESCRIPTION
**Pull request by alfredbirk**

### CODE REVIEW

**Comment by joakikr** [comment]
Will this still work on small devices? And also, missing the vertical line from the design 👍

**Comment by alfredbirk** [comment]
> Will this still work on small devices? And also, missing the vertical line from the design 👍

Yep, works on small devices too. I added the vertical line now

**Comment by joakikr** [comment]
Screen Shot 2020-03-16 at 12 46 38

The quantity picker looks weird now 😅

**Comment by alfredbirk** [comment]
> Screen Shot 2020-03-16 at 12 46 38
> 
> The quantity picker looks weird now 😅

The Button style I modified was also used by the quantity picker 😌 Should be fixed now I think.

**Pull request merged**
