### PR TITLE
Fix icon paths

### PR DESCRIPTION
**Pull request by richiewenn**

### CODE REVIEW

**Comment by cathrholm** [comment]
I get these errors when i try running this branch:
ERROR in ./component-lib/src/organisms/ContentRating/ContentRating.jsx
Module not found: Error: Can't resolve '../assets/icons/ico_heart.svg' in 'C:\Users\cathrine.holm\Projects\styleguide\component-lib\src\organisms\ContentRating'
 @ ./component-lib/src/organisms/ContentRating/ContentRating.jsx 21:17-57
 @ ./component-lib/src/index.js
 @ ./src/client/Routes.js
 @ ./src/client/App.js
 @ ./src/client/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8090 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8090 webpack/hot/only-dev-server ./index.js whatwg-fetch

ERROR in ./component-lib/src/molecules/PageMenu/MenuItem.jsx
Module not found: Error: Can't resolve '../assets/icons/ico_linkarrow.svg' in 'C:\Users\cathrine.holm\Projects\styleguide\component-lib\src\molecules\PageMenu'
 @ ./component-lib/src/molecules/PageMenu/MenuItem.jsx 18:24-68
 @ ./component-lib/src/molecules/PageMenu/MenuBar.jsx
 @ ./component-lib/src/molecules/PageMenu/PageMenu.jsx
 @ ./component-lib/src/molecules/PageHeader/PageHeader.jsx
 @ ./component-lib/src/index.js
 @ ./src/client/Routes.js
 @ ./src/client/App.js
 @ ./src/client/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8090 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8090 webpack/hot/only-dev-server ./index.js whatwg-fetch
webpack: Failed to compile.

**Comment by alexyork** [comment]
Can you elaborate on what is going on here, and why this change was needed? i.e. what problem it solved.

**Comment by richiewenn** [comment]
The icons did not work in our case. The code expects us to have icons at /public/icons/whatever.svg. This PR is here to fix that using require function.

**Comment by alexyork** [comment]
I think this is no longer relevant

**Pull request closed without merging**
